server:
#  port: 8081
  error:
    include-message: always
    include-binding-error: always

spring:
  datasource:
    password: 532000
    url: jdbc:mysql://localhost:3306/corelia_task
    username: banna
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
jwt:
  secret: mahmoud_elbanna
  expiration: 3600000